source_dataset_path: null   # leave blank to default to what is already hard coded in the notebook, & use / instead of \
reviewed_data_destn: null   # leave blank to default to what is already hard coded in the notebook, & use / instead of \
naming_csv: null            # leave blank to default to project_root/data/bird_names/bird_names.csv, & use / instead of \
                            # (csv must include eBird and CommonName columns, and Unknown | unknown)

author: Godzilla       # use Author for first annotation, otherwise leave as null below
reviewer: null     # use Reviewer for subsequent corrections/additions

map_extents: new_zealand    # must match a key in geographic_extents  currently 'new_zealand' and 'south_america'
display_width: 13           # adjust for screen size